### ISSUE TITLE
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

### ISSUE THREAD

**Issue by dnvs** [Kiteretsu77/APISR#11]
hope support mac ...

**Comment by Kiteretsu77** [comment]
Thanks for the report! I will try my best to add a feature to be capable of doing inference on CPU-only devices. Meanwhile, in [ComfyUI-APISR](https://github.com/ZHO-ZHO-ZHO/ComfyUI-APISR), they have provided a way to use the CPU. However, this repo is in Chinese. You can have a look at that and it may be possible that it is adaptive to Mac.
Another solution is to use the [colab](https://colab.research.google.com/github/camenduru/APISR-jupyter/blob/main/APISR_jupyter.ipynb) provided to use free account credit from Google to do inference online

**Comment by alexaex** [comment]
I have resolved this issue.  You just need to add a few lines of code like the screenshots. I've tried this and I'm able to successfully run the inference on a MacBook Air M2.
![image](https://github.com/Kiteretsu77/APISR/assets/93668251/ca50024f-f7bb-4946-b618-b9af010d1b41)
![image](https://github.com/Kiteretsu77/APISR/assets/93668251/9dae4e1a-8416-4122-86ce-64ec48c3cf61)
![image](https://github.com/Kiteretsu77/APISR/assets/93668251/2b3dc8ab-aa24-40d4-a883-b315eb4b00fb)
![image](https://github.com/Kiteretsu77/APISR/assets/93668251/f2625c8f-e074-4d2a-b75a-bd060cc2147b)
